### ISSUE TITLE
Getting An error has occurred during metrics gathering:

### ISSUE THREAD

**Issue by jasvinder374** [wakeful/kafka_connect_exporter#1]
HI, I have setup kafka_connect_exporter, it was working fine, suddenly got an error on all brokers, which is define below. I have setup this in centos 7 and defined the service as:

cat /etc/systemd/system/kafka_connect_exporter.service
[Unit]
Description=Kafka Connect Exporter

[Service]
User=kafka_connect_exporter
ExecStart=/usr/local/bin/kafka_connect_exporter  \
  -scrape-uri "http://10.51.12.30:8083" \
  --listen-address ":9194"

SyslogIdentifier=kafka_exporter
Restart=always
RestartSec=90
StartLimitInterval=400
StartLimitBurst=3

[Install]
WantedBy=multi-user.target

When I curl, getting below exception:

An error has occurred during metrics gathering:

2 error(s) occurred:
* collected metric kafka_connect_connector_tasks_state_running label:<name:"connector" value:"elastic-sink-connect-02" > label:<name:"state" value:"running" > label:<name:"worker_id" value:"10.51.12.223:8083" > gauge:<value:1 >  was collected before with the same name and label values
* collected metric kafka_connect_connector_tasks_state_running label:<name:"connector" value:"elastic-sink-connect-02" > label:<name:"state" value:"running" > label:<name:"worker_id" value:"10.51.12.30:8083" > gauge:<value:1 >  was collected before with the same name and label values
[root@data-pipeline-kafka-prod-2 log]# debug1: client_input_channel_req: channel 0 rtype keepalive@openssh.com reply 1

**Comment by jasvinder374** [comment]
Can someone update please

**Comment by wakeful** [comment]
hello,

could you share `elastic-sink-connect-0` connector configuration?
what version of **kafka connect** are you using?

**Comment by jasvinder374** [comment]
elastic-sink-connect config:

{"name":"elastic-sink-connect-02","config":{"connector.class":"io.confluent.connect.elasticsearch.ElasticsearchSinkConnector","type.name":"changedata","transforms.dedupe.field2diff":"dataafter","transforms.dedupe.preserveoriginal":"true","tasks.max":"5","group.id":"auditinfo","batch.size":"300","transforms":"dedupe","key.ignore":"true","topics.regex":"platmysqlslave.bazaarify.*","transforms.dedupe.field1diff":"databefore","schema.ignore":"true","transforms.dedupe.field2":"data.after","flush.timeout.ms":"60000","name":"elastic-sink-connect-02","transforms.dedupe.donotcomparefields":"id,business_id,template_id","connection.url":"https://vpc-prod-birdeye-devops-es-77.us-west-1.es.amazonaws.com","transforms.dedupe.type":"com.birdeye.transformer.Dedupe","transforms.dedupe.field1":"data.before"},"tasks":[{"connector":"elastic-sink-connect-02","task":0},{"connector":"elastic-sink-connect-02","task":1},{"connector":"elastic-sink-connect-02","task":2},{"connector":"elastic-sink-connect-02","task":3},{"connector":"elastic-sink-connect-02","task":4}],"type":"sink"}


version : kafka_2.12-2.1.0

**Comment by jasvinder374** [comment]
and this setup has done with 3 Kafka Connect node.

**Comment by jasvinder374** [comment]
what I found, the value of "tasks.max":"5" is causing the issue, when we define this value to 3 or equal the number of kafka_connect, then it works fine, when we increase this value, it gives the error:

An error has occurred during metrics gathering:

2 error(s) occurred:
* collected metric kafka_connect_connector_tasks_state_running label:<name:"connector" value:"elastic-sink-connect-03" > label:<name:"state" value:"running" > label:<name:"worker_id" value:"10.51.12.33:8083" > gauge:<value:1 >  was collected before with the same name and label values
* collected metric kafka_connect_connector_tasks_state_running label:<name:"connector" value:"elastic-sink-connect-03" > label:<name:"state" value:"running" > label:<name:"worker_id" value:"10.51.12.30:8083" > gauge:<value:1 >  was collected before with the same name and label values

**Comment by wakeful** [comment]
ok let me try build a fix

**Comment by jasvinder374** [comment]
Hi,
  Did you get a chance to fix it ?

**Comment by imriz** [comment]
proposed fix is in https://github.com/wakeful/kafka_connect_exporter/pull/2

**Comment by wakeful** [comment]
@imriz thanks for the fix, @jasvinder374 can you check with [0.1.1](https://github.com/wakeful/kafka_connect_exporter/releases/tag/0.1.1) build?
